## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Maries und Constantins Hochzeit"
theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
# baseURL = "/"
# publishDir = "public"

# Remote
baseURL = "https://cundm.github.io/MyWedding/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]